name: Deploy to Vercel

on:
    push:
        branches: [main, preview]
    pull_request:
        branches: [main, preview]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Vercel Action ${{ secrets.VERCEL_TOKEN }}
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: 7897hFCy30msbQEZLlb6RlA2
          vercel-org-id: 0jWMrx8I2vraypGGJ6rELgoN
          vercel-project-id: prj_BLAtoGyLgIyHLzbBFviVDxFuTvFE
